sonar.organization=GSUSA
sonar.projectKey=gsusa-vtk-redesign-nextjs
sonar.projectName=GSUSA VTK Redesign Next.js
sonar.projectVersion=1.0

# Sources
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__tests__/**/*, **/*.test.js

# Code coverage
sonar.coverage.exclusions=**/node_modules/**,**/.storybook/**,**/.next/**,**/*.styles.*,**/*.spec.*,**/*.stories.*,__mocks__/**/*,*.config.*,__tests__/**/*,lib/**/*,public/**,src/pages/_app.tsx,src/pages/_document.tsx,
sonar.dynamicAnalysis=reuseReports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
