import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  neutral100: '#1A1A1A',
  neutral90: '#333333',
  neutral80: '#4D4D4D',
  neutral70: '#666666',
  neutral60: '#808080',
  neutral20: '#D9D9D9',
  neutral10: '#F2F2F2',
  white: '#FFFFFF',
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 90,
    paddingHorizontal: 36,
    fontFamily: 'Poppins',
    color: colors.neutral100,
    fontSize: 10,
    backgroundColor: colors.white,
  },
  fullHeader: {
    flexDirection: 'column',
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.neutral90,
    marginBottom: 14,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 8,
  },
  headerLeft: { flexDirection: 'row', gap: 10, flex: 1, alignItems: 'flex-start' },
  headerLeftCol: { flex: 1, flexDirection: 'column', gap: 3 },
  // Fixed-width right column so long names in the multi-level groups box
  // wrap to multiple lines instead of pushing the hero copy on the left.
  headerRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 8,
    flexShrink: 0,
    width: 220,
  },
  programLevelsRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'flex-end',
    gap: 6,
  },
  badgeImage: { width: 64, height: 64, objectFit: 'contain' },
  breadcrumb: {
    fontWeight: 600,
    fontSize: 7,
    color: colors.neutral60,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  title: {
    fontFamily: 'Poppins',
    fontWeight: 700,
    fontSize: 22,
    color: colors.neutral100,
    lineHeight: 1.15,
  },
  description: { fontSize: 9, color: colors.neutral70, lineHeight: 1.4 },
  pillProgramLevel: {
    paddingTop: 4,
    paddingBottom: 3,
    paddingLeft: 7,
    paddingRight: 3,
    borderWidth: 1.5,
    borderColor: colors.neutral100,
    borderRadius: 100,
    fontWeight: 700,
    fontSize: 8,
    lineHeight: 1,
    letterSpacing: 0.5,
    color: colors.neutral100,
    textTransform: 'uppercase',
  },
  relatedBox: {
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 4,
    padding: 6,
    width: '100%',
    flexDirection: 'column',
    gap: 3,
    // White content area under the colored title bar (color mode).
    backgroundColor: colors.white,
  },
  relatedLabel: {
    fontWeight: 700,
    fontSize: 7,
    color: colors.neutral70,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  relatedItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 6,
  },
  relatedName: { fontWeight: 600, fontSize: 8, color: colors.neutral90, flex: 1, flexShrink: 1, lineHeight: 1.3 },
  relatedLevel: {
    fontSize: 8,
    color: colors.neutral60,
    fontStyle: 'italic',
    textAlign: 'right',
    maxWidth: 80,
    lineHeight: 1.3,
  },
  sectionHeading: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 6 },
  sectionTitle: {
    fontFamily: 'Poppins',
    fontWeight: 700,
    fontSize: 13,
    color: colors.neutral100,
  },
  sectionSubtitle: { fontSize: 9, color: colors.neutral60 },
  miniHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: colors.neutral90,
    marginBottom: 12,
  },
  miniBadgeImage: { width: 52, height: 52, objectFit: 'contain' },
  miniHeaderText: { flexDirection: 'column', gap: 3, flex: 1 },
  miniTitle: { fontFamily: 'Poppins', fontWeight: 700, fontSize: 18, color: colors.neutral100 },
  block: { marginBottom: 8 },
  directiveBlock: { flexDirection: 'column', gap: 4 },
  card: {
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 4,
    padding: 10,
    flexDirection: 'column',
    gap: 6,
  },
  cardTitle: {
    fontWeight: 700,
    fontSize: 11,
    color: colors.neutral100,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral20,
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
  },
  stepHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  stepBubble: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.neutral20,
    fontWeight: 700,
    fontSize: 10,
    color: colors.neutral100,
    textAlign: 'center',
    paddingTop: 2,
  },
  stepName: { fontWeight: 600, fontSize: 11, color: colors.neutral100 },
  stepComplete: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  checkbox: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 2,
  },
  checkboxSmall: {
    width: 8,
    height: 8,
    borderWidth: 1,
    borderColor: colors.neutral60,
    borderRadius: 1,
    marginTop: 2,
  },
  stepCompleteLabel: { fontSize: 7, lineHeight: 1.4, color: colors.neutral60, textAlign: 'center' },
  stepDescription: { fontSize: 9, color: colors.neutral70, lineHeight: 1.45 },
  activityIdeas: {
    backgroundColor: colors.neutral10,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 3,
    paddingVertical: 6,
    paddingHorizontal: 8,
    flexDirection: 'column',
    gap: 3,
  },
  activityIdeasLabel: {
    fontWeight: 700,
    fontSize: 8,
    color: colors.neutral70,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  activityItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  activityName: { fontWeight: 500, fontSize: 9, color: colors.neutral100, lineHeight: 1.2 },
  closingQuestionBlock: {
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 4,
    padding: 9,
    flexDirection: 'column',
    gap: 5,
  },
  closingQuestionTitle: {
    fontWeight: 600,
    fontSize: 12,
    color: colors.neutral100,
  },
  closingQuestionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 3,
    padding: 8,
  },
  closingQuestionIcon: {
    fontWeight: 700,
    fontSize: 14,
    color: colors.neutral20,
    lineHeight: 1.4,
    paddingHorizontal: 5,
  },
  closingQuestionText: { fontWeight: 600, fontSize: 9, color: colors.neutral100, flex: 1, lineHeight: 1.4 },
  handoutsBlock: {
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 4,
    padding: 9,
    flexDirection: 'column',
    gap: 6,
  },
  handoutsHeading: { flexDirection: 'row', alignItems: 'baseline', gap: 6 },
  handoutsTitle: { fontWeight: 600, fontSize: 12, lineHeight: 1, color: colors.neutral100 },
  handoutsCount: {
    fontWeight: 600,
    fontSize: 8,
    lineHeight: 1,
    color: colors.neutral60,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  handoutsSubtitle: { fontSize: 9, color: colors.neutral60, lineHeight: 1.4 },
  contentModuleBlock: {
    flexDirection: 'column',
    gap: 3,
    marginTop: 4,
  },
  calloutPdfBlock: {
    flexDirection: 'column',
    gap: 3,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 3,
    backgroundColor: colors.white,
  },
  calloutPdfTitle: { fontWeight: 600, fontSize: 10, color: colors.neutral100 },
  calloutPdfSubtitle: { fontWeight: 600, fontSize: 9, color: colors.neutral80 },
  calloutPdfRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  calloutPdfIcon: {
    width: 28,
    height: 28,
    borderRadius: 4,
    backgroundColor: colors.neutral10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  calloutPdfIconImg: { width: 20, height: 20, objectFit: 'contain' },
  calloutPdfContent: { flex: 1, flexDirection: 'column', gap: 3 },
  filePdfBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 6,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 6,
    backgroundColor: colors.neutral10,
    minHeight: 20,
  },
  filePdfIcon: {
    width: 16,
    height: 16,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  filePdfTitle: { fontWeight: 400, fontSize: 10, lineHeight: 1.2, color: colors.neutral100, flex: 1 },
  handoutsList: {
    flexDirection: 'column',
    gap: 4,
  },
  handoutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 6,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 6,
    backgroundColor: colors.white,
    minHeight: 20,
  },
  handoutItemIcon: {
    width: 16,
    height: 16,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  handoutName: { fontWeight: 400, fontSize: 10, lineHeight: 1.2, color: colors.neutral100, flex: 1 },
  handoutUnit: { fontSize: 8, color: colors.neutral60, textAlign: 'right', flexShrink: 0 },
  handoutIcon: {
    width: 9,
    height: 11,
    backgroundColor: colors.neutral70,
  },
  supplies: {
    backgroundColor: colors.neutral10,
    borderWidth: 1.5,
    borderColor: colors.neutral100,
    borderRadius: 5,
    padding: 8,
    flexDirection: 'column',
    gap: 6,
  },
  suppliesHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral20,
  },
  suppliesCols: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  suppliesCol: { flex: 1, flexDirection: 'column', gap: 4 },
  suppliesDivider: { width: 1, backgroundColor: colors.neutral20, alignSelf: 'stretch' },
  suppliesOptionalLabel: {
    fontWeight: 700,
    fontSize: 7,
    color: colors.neutral60,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  supplyItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  supplyLabel: { fontSize: 9, color: colors.neutral100, flex: 1, lineHeight: 1.3 },
  supplyQuantity: { fontSize: 8, color: colors.neutral60 },
  supplyBlankLine: {
    flex: 1,
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral70,
    marginLeft: 4,
  },
  numberedItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginBottom: 6 },
  numberBubble: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.neutral20,
    fontWeight: 700,
    fontSize: 9,
    color: colors.neutral100,
    textAlign: 'center',
    paddingTop: 2,
    flexShrink: 0,
  },
  numberedItemText: { fontSize: 10, color: colors.neutral100, flex: 1, lineHeight: 1.35 },
  cardDescription: { fontSize: 9, color: colors.neutral70, lineHeight: 1.45 },
  contentImage: {
    maxWidth: '100%',
    maxHeight: 180,
    objectFit: 'contain',
    borderRadius: 4,
    marginBottom: 6,
    alignSelf: 'center',
  },
  timeRange: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 6,
    marginTop: 4,
  },
  timeText: { fontWeight: 600, fontSize: 8, color: colors.neutral80 },
  donorBlock: {
    flexDirection: 'column',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.neutral20,
    borderRadius: 4,
    padding: 10,
  },
  donorTitle: { fontWeight: 600, fontSize: 10, color: colors.neutral100, marginBottom: 3 },
  donorLogo: {
    maxWidth: 140,
    maxHeight: 60,
    objectFit: 'contain',
    marginBottom: 6,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 36,
    right: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.neutral20,
  },
  footerQr: { width: 44, height: 44 },
  footerInfo: { flex: 1, flexDirection: 'column', gap: 1 },
  footerLabel: { fontWeight: 600, fontSize: 8, color: colors.neutral80 },
  footerUrl: { fontSize: 7, color: colors.neutral60 },
  footerCopyright: { fontSize: 6, color: colors.neutral60, marginTop: 2 },
  footerPage: { fontWeight: 600, fontSize: 8, color: colors.neutral70 },
});

// Color-mode override: a filled program-level header bar that bleeds to the
// card edges. `pad`/`radius` must match the host card.
export const sectionHeaderBar = (levelBg: string, levelText: string, pad: number, radius: number) => ({
  backgroundColor: levelBg,
  color: levelText,
  marginTop: -pad,
  marginLeft: -pad,
  marginRight: -pad,
  marginBottom: 4,
  paddingVertical: 5,
  paddingHorizontal: pad,
  borderTopLeftRadius: radius,
  borderTopRightRadius: radius,
  borderBottomWidth: 0,
});

// Color-mode override: fills the top header band with the program-level tint,
// bleeding to the top page edge and cropped at the divider.
export const heroHeaderTint = (tint: string) => ({
  backgroundColor: tint,
  marginTop: -36,
  paddingTop: 36,
  // Crop the absolutely-positioned decorative shapes to the band.
  position: 'relative' as const,
  overflow: 'hidden' as const,
});

export const htmlStylesheet: Record<string, object> = {
  p: { margin: 0, marginBottom: 4, fontSize: 9, color: colors.neutral70, lineHeight: 1.45 },
  strong: { fontWeight: 700, color: colors.neutral100 },
  b: { fontWeight: 700, color: colors.neutral100 },
  em: { fontStyle: 'italic' },
  i: { fontStyle: 'italic' },
  a: { color: colors.neutral70, textDecoration: 'none', fontWeight: 'normal' },
  ul: { marginVertical: 4, paddingLeft: 12 },
  ol: { marginVertical: 4, paddingLeft: 12 },
  li: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 3,
    fontSize: 9,
    color: colors.neutral70,
    lineHeight: 1.4,
  },
  h1: { fontWeight: 700, fontSize: 14, color: colors.neutral100, marginBottom: 4 },
  h2: { fontWeight: 700, fontSize: 13, color: colors.neutral100, marginBottom: 4 },
  h3: { fontWeight: 700, fontSize: 12, color: colors.neutral100, marginBottom: 4 },
  h4: { fontWeight: 600, fontSize: 11, color: colors.neutral100, marginBottom: 3 },
  img: {
    maxWidth: '100%',
    maxHeight: 180,
    objectFit: 'contain',
    marginVertical: 6,
    alignSelf: 'center',
  },
};
